---
grails:
    profile: web
    codegen:
        defaultPackage: tmf.host
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
        buildDate: '@info.app.buildDate@'
spring:
    groovy:
        template:
            check-template-location: false

---
server:
    port: 8080
---
grails:
    assets:
        bundle: false
    gorm:
        failOnError: true
        autoFlush: true
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none

    gsp:
        tldScanPattern: classpath*:/META-INF/*.tld
---
hibernate:
    cache:
        use_second_level_cache: true
        use_query_cache: true
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'
    search:
        default:
            indexBase: '/opt/tpat/lucene'
            indexmanager: near-real-time
            directory_provider: filesystem

endpoints:
    jmx:
        unique-names: true

dataSource:
    pooled: true
    jmxExport: true
#    driverClassName: net.sf.log4jdbc.DriverSpy
    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://aapc_mysql_host:3306/tfam_dev?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true
#   TPAT For TAT DB Settings
#    url: jdbc:mysql://tpatfortatDatabase:3306/tpat_db
#    username: tpat_user
#    password: tpat_pw_11
#   Prod Settings
#    url: jdbc:mysql://tpatDatabase:3306/tpat_db
#    username: tpat_user
#    password: tpat_pw_11
#   Normal Dev DB Settings
    url: jdbc:mysql://tpat_database:3306/tfam_dev
    username: tfam
    password: tfam_11
    dialect: tmf.host.util.CustomMysqlDialect
    properties: 
      testWhileIdle: true
      testOnBorrow: true
      autoReconnect: true
      initialSize: 5
      maxActive: 8
      minIdle: 5
      maxIdle: 8
      validationInterval: 450

environments:
    development:
        dataSource:
            dbCreate: update
    test:
        dataSource:
            dbCreate: update
    production:
        dataSource:
            dbCreate: update


---
quartz:
    autoStartup: true
